; This file is a part of CuteMouse source
; Pointer table to support SBCS and DBCS in dual languages.
TE_needvga	equ E_needvga
TE_error	equ E_error
TE_option	equ E_option
TE_argument	equ E_argument
TE_help	equ E_help
TE_mousepresent	equ E_mousepresent
TE_notfound	equ E_notfound
;;+TE_noIRQ	equ E_noIRQ
TE_nocute	equ E_nocute
TE_notunload	equ E_notunload
TS_unloaded	equ S_unloaded
TS_reset	equ S_reset
TS_installed	equ S_installed
TS_atPS2	equ S_atPS2
TS_atCOM	equ S_atCOM
TS_atIO	equ S_atIO
TS_in	equ S_in
TS_inMSYS	equ S_inMSYS
TS_inMS	equ S_inMS
TS_inLT	equ S_inLT
TS_wheel	equ S_wheel
TS_CRLF	equ S_CRLF
TCopyright	equ Copyright
TSyntax	equ Syntax
