; This file is a part of CuteMouse source
; Pointer table to support SBCS and DBCS in dual languages.
TE_needvga	dw  dataref:E_needvga
		dw  dataref:DE_needvga
TE_error	dw  dataref:E_error
		dw  dataref:DE_error
TE_option	dw  dataref:E_option
		dw  dataref:DE_option
TE_argument	dw  dataref:E_argument
		dw  dataref:DE_argument
TE_help	dw  dataref:E_help
		dw  dataref:DE_help
TE_mousepresent	dw  dataref:E_mousepresent
		dw  dataref:DE_mousepresent
TE_notfound	dw  dataref:E_notfound
		dw  dataref:DE_notfound
;;+TE_noIRQ	dw  dataref:E_noIRQ
;;		dw  dataref:DE_noIRQ
TE_nocute	dw  dataref:E_nocute
		dw  dataref:DE_nocute
TE_notunload	dw  dataref:E_notunload
		dw  dataref:DE_notunload
TS_unloaded	dw  dataref:S_unloaded
		dw  dataref:DS_unloaded
TS_reset	dw  dataref:S_reset
		dw  dataref:DS_reset
TS_installed	dw  dataref:S_installed
		dw  dataref:DS_installed
TS_atPS2	dw  dataref:S_atPS2
		dw  dataref:DS_atPS2
TS_atCOM	dw  dataref:S_atCOM
		dw  dataref:DS_atCOM
TS_atIO	dw  dataref:S_atIO
		dw  dataref:DS_atIO
TS_in	dw  dataref:S_in
		dw  dataref:DS_in
TS_inMSYS	dw  dataref:S_inMSYS
		dw  dataref:DS_inMSYS
TS_inMS	dw  dataref:S_inMS
		dw  dataref:DS_inMS
TS_inLT	dw  dataref:S_inLT
		dw  dataref:DS_inLT
TS_wheel	dw  dataref:S_wheel
		dw  dataref:DS_wheel
TS_CRLF	dw  dataref:S_CRLF
		dw  dataref:DS_CRLF
TCopyright	dw  dataref:Copyright
		dw  dataref:DCopyright
TSyntax	dw  dataref:Syntax
		dw  dataref:DSyntax
